export const stockSuggestions = [
  { symbol: "AAPL", name: "Apple Inc.", price: 180.25, annualDividend: 0.92 },
  { symbol: "MSFT", name: "Microsoft Corporation", price: 372.65, annualDividend: 2.72 },
  { symbol: "GOOGL", name: "Alphabet Inc.", price: 142.5, annualDividend: 0 },
  { symbol: "AMZN", name: "Amazon.com Inc.", price: 178.75, annualDividend: 0 },
  { symbol: "META", name: "Meta Platforms Inc.", price: 485.2, annualDividend: 0 },
  { symbol: "TSLA", name: "Tesla Inc.", price: 175.3, annualDividend: 0 },
  { symbol: "JNJ", name: "Johnson & Johnson", price: 158.2, annualDividend: 4.76 },
  { symbol: "PG", name: "Procter & Gamble Co.", price: 153.5, annualDividend: 3.76 },
  { symbol: "KO", name: "Coca-Cola Company", price: 61.25, annualDividend: 1.84 },
  { symbol: "PEP", name: "PepsiCo Inc.", price: 172.4, annualDividend: 5.06 },
  { symbol: "VZ", name: "Verizon Communications Inc.", price: 39.0, annualDividend: 2.61 },
  { symbol: "T", name: "AT&T Inc.", price: 17.6, annualDividend: 1.11 },
  { symbol: "XOM", name: "Exxon Mobil Corporation", price: 101.2, annualDividend: 3.64 },
  { symbol: "CVX", name: "Chevron Corporation", price: 151.0, annualDividend: 6.04 },
  { symbol: "JPM", name: "JPMorgan Chase & Co.", price: 166.5, annualDividend: 4.0 },
  { symbol: "BAC", name: "Bank of America Corp.", price: 37.8, annualDividend: 0.96 },
  { symbol: "WMT", name: "Walmart Inc.", price: 59.8, annualDividend: 0.83 },
  { symbol: "HD", name: "Home Depot Inc.", price: 342.3, annualDividend: 8.36 },
  { symbol: "DIS", name: "Walt Disney Co.", price: 103.25, annualDividend: 0 },
  { symbol: "NFLX", name: "Netflix Inc.", price: 625.8, annualDividend: 0 },
]
